name: CI for Hello World

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    step:
    - uses: actions/steup-python@v2
      with:
        python-version: 3.8
    - name: Install Libraries
      run: |
        pip install flake8 pytest pytest-cov
    - name: Checkout Own Repo
      uses: actions/checkout@v2
      with:
        repository: DevOps-TeamTwo-2022/DevOps_Oct2022_Team2_Week4
    - name: list our contents
      run: |
        ls
